version: '3'

services:
  orderdb:
    image: postgres:16.0-alpine3.18
    container_name: order-service
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: username1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: order_service
    volumes:
      - order:/var/lib/postgresql/data

  mongo:
    ports:
      - '27017:27017'
    container_name: product-service
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      MONGO_INITDB_ROOT_USERNAME: username1
      MONGO_INITDB_ROOT_PASSWORD: password1
      MONGO_INITDB_ROOT_DATABASE: product-service
    image: mongo
    volumes:
      - dbdata6:/data/db

  inventorydb:
    image: postgres:16.0-alpine3.18
    container_name: inventory-service
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: username1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: inventory_service
    volumes:
      - inventory:/var/lib/postgresql/data

volumes:
  order:
  dbdata6:
  inventory: