version: '3'

services:
#######################################################################################################################
  orderdb:
    image: postgres:16.0-alpine3.18
    container_name: order-service
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: username1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: order_service
    volumes:
      - order:/var/lib/postgresql/data
#######################################################################################################################
  mongo:
    ports:
      - '27017:27017'
    container_name: product-service
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      MONGO_INITDB_ROOT_USERNAME: username1
      MONGO_INITDB_ROOT_PASSWORD: password1
      MONGO_INITDB_ROOT_DATABASE: product-service
    image: mongo
    volumes:
      - dbdata6:/data/db
#######################################################################################################################
  inventorydb:
    image: postgres:16.0-alpine3.18
    container_name: inventory-service
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: username1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: inventory_service
    volumes:
      - inventory:/var/lib/postgresql/data
#######################################################################################################################
  auth:
    image: quay.io/keycloak/keycloak:18.0.0
    ports:
      - "8181:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    volumes:
      - auth:/opt/keycloak/data/import/realm.json
#######################################################################################################################
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
#######################################################################################################################
  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#######################################################################################################################

volumes:
  order:
  dbdata6:
  inventory:
  auth: